### ISSUE TITLE
Suggestions and Bugs

### ISSUE THREAD

**Issue by Slothswithaids** [CMD-X/CMD-X#60]
**Bugs;**
- Bring command
- tp (user) (user)
- Invisible command
_(There are many other commands that aren't working)_

**Suggestions;**
- Add a fling command.
- Add other troll commands.

**Comment by CMD-X** [comment]
Bring command, is working just fine (I have tested in the correct env, make sure your are R6 and you have a tool and your target is not evading you at high speeds) (bring (plr))
Fling command, is already a thing. (ffling, fling (plr), cfling, ifling)

Invisible I already know is broken it will be fixed in V2.

We currently aren't adding multi-tp support, but we will think of a way to efficiently do this in V2, to move a player they need to be forced with a tool so it would be qute finicky to add multi-tp support.

Thanks for your suggestions!
